### ISSUE TITLE
Bamboo 9.5.0 is not supported

### ISSUE THREAD

**Issue by tomkeiev** [allure-framework/allure-bamboo#338]
After updating Bamboo to 9.5 the **UI** part stopped working. Reports can still be accessible via URL but the tab in Bamboo isn't displayed. It looks like Bamboo got rid of some necessary for Allure dependencies so I hope the fix is quick and easy.
Here is the error stack trace:

> [DefaultWebInterfaceManager] Could not evaluate condition 'io.qameta.allure.bamboo.AllureViewReportCondition@6bf7ecd5' for descriptor: io.qameta.allure.allure-bamboo:allure:${immutablePlan.key}-${resultsSummary.buildNumber} (null)
java.lang.NoClassDefFoundError: org/sonatype/aether/util/StringUtils
	at io.qameta.allure.bamboo.AllureBuildResult.hasInfo(AllureBuildResult.java:86) ~[?:?]
	at io.qameta.allure.bamboo.AllureViewReportCondition.shouldDisplay(AllureViewReportCondition.java:57) ~[?:?]
	at com.atlassian.plugin.web.DefaultWebInterfaceManager.filterFragmentsByCondition(DefaultWebInterfaceManager.java:184) ~[atlassian-plugins-webfragment-6.0.1.jar:?]
	at com.atlassian.plugin.web.DefaultWebInterfaceManager.getDisplayableItems(DefaultWebInterfaceManager.java:138) ~[atlassian-plugins-webfragment-6.0.1.jar:?]
	at com.atlassian.bamboo.ww2.BambooActionSupport.getWebItemsForSection(BambooActionSupport.java:459) ~[atlassian-bamboo-web-9.5.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1553) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:73) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.MethodCall._eval(MethodCall.java:75) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.Expression.eval(Expression.java:101) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.Assignment.accept(Assignment.java:134) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.Environment.visit(Environment.java:383) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:657) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.Environment.visit(Environment.java:383) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:889) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.Environment.invokeMacro(Environment.java:825) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:87) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.Environment.visit(Environment.java:347) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.Environment.visit(Environment.java:389) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:889) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.Environment.invokeMacro(Environment.java:825) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:87) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.Environment.visit(Environment.java:383) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.Environment.visit(Environment.java:410) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.BlockAssignment.accept(BlockAssignment.java:55) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.Environment.visit(Environment.java:347) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.Environment.visit(Environment.java:353) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.Environment.visit(Environment.java:353) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.core.Environment.process(Environment.java:326) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at freemarker.template.Template.process(Template.java:383) ~[freemarker-2.3.31-atlassian-2.jar:2.3.31]
	at com.atlassian.bamboo.ww2.FreemarkerRequestDispatcherPageFilter.applyDecorator(FreemarkerRequestDispatcherPageFilter.java:123) ~[atlassian-bamboo-web-9.5.0.jar:?]
	at org.apache.struts2.sitemesh.TemplatePageFilter.applyDecorator(TemplatePageFilter.java:116) ~[struts2-sitemesh-plugin-2.1.8.1.jar:?]
	at com.atlassian.bamboo.ww2.FreemarkerRequestDispatcherPageFilter.access$000(FreemarkerRequestDispatcherPageFilter.java:46) ~[atlassian-bamboo-web-9.5.0.jar:?]
	at com.atlassian.bamboo.ww2.FreemarkerRequestDispatcherPageFilter$BambooSitemeshDecorator.render(FreemarkerRequestDispatcherPageFilter.java:245) ~[atlassian-bamboo-web-9.5.0.jar:?]
	at com.opensymphony.sitemesh.webapp.decorator.BaseWebAppDecorator.render(BaseWebAppDecorator.java:33) ~[sitemesh-2.5-atlassian-11.jar:?]
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:92) ~[sitemesh-2.5-atlassian-11.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.83]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.83]
	at com.atlassian.bamboo.filter.SessionCreationForAnonymousUserFilter.doFilter(SessionCreationForAnonymousUserFilter.java:40) ~[atlassian-bamboo-web-9.5.0.jar:?]

**Comment by vbragin** [comment]
Please try 1.18.0
