### ISSUE TITLE
Plugin not working with Bamboo 8.1?

### ISSUE THREAD

**Issue by samuelb** [allure-framework/allure-bamboo#241]
Hello

We upgraded our Bamboo Server installation to 8.1.1 the other day and found the plugin "Allure Report for Bamboo" to not load anymore. The [Atlassian Marketplace](https://marketplace.atlassian.com/apps/1217177/allure-report-for-bamboo?tab=overview&hosting=server) shows today that the plugin is compatible with version Bamboo 8.1.1.

The logs say:
```
2021-12-23 12:07:24,111 ERROR [UpmAsynchronousTaskManager:thread-1] [DefaultPluginManager] There was an error loading the descriptor 'Allure Report Configuration' of plugin 'io.qameta.allure.allure-bamboo'. Disabling.
java.lang.NoClassDefFoundError: com/atlassian/bamboo/v2/build/configuration/MiscellaneousBuildConfigurationPlugin
```

**Comment by vrosansys** [comment]
Same error after upgrading to  8.1.1

**Comment by RSV7** [comment]
Not sure who is an admin here but the issue hasn't been answered 11 days... maybe @eroshenkoam could you assist, please?

**Comment by vbragin** [comment]
Will be fixed in future release
